- src/commands/ft_create_parser.cc
- testing/ft_create_parser_test.cc
- vmsdk/src/utils.cc
- vmsdk/src/utils.h
- vmsdk/testing/utils_test.cc
Enhance vmsdk with a ParseHashTag function.
Modified FT.CREATE to disallow index names or prefix values to contain a hash tag.
> Ensure that Index names and Prefixes do not have a slot tag, closes #31

- src/commands/filter_parser.cc
- src/indexes/numeric.cc
- vmsdk/src/type_conversions.h
absl::SimpleAtod has a special handling for "nan" where it returns true but copy "nan" to the out value. Addressing this by checking for the string "nan".
This PR addresses the issue described in https://github.com/valkey-io/valkey-search/issues/53
> Fix parsing double/float from string

- cmake/Modules/valkey_search.cmake
- vmsdk/src/utils.h
- CMake: explicitly link against pthread
- Add missing include header (`optional`) when building on aarch64
> Small aarch64 fixes

- build.sh
- src/CMakeLists.txt
- third_party/hnswlib/CMakeLists.txt
The crash was caused due to hnswlib not using
the memory override methods (CMake only).
Details:
- Any library consuming `hnswlib` will now have the macro `VMSDK_ENABLE_MEMORY_ALLOCATION_OVERRIDES` set during build time.
- Use version script `vmsdk/versionscript.lds`
- Fixed `build.sh --clean` when the build folder does not exist
> Fixed crash when loading RDB

- .github/workflows/integration_tests.yml
- .github/workflows/unittests.yml
- testing/valkey_search_test.cc
Fixes:
1. Running the docker in github workspaces as a privileged user.
2. Fixing valkey_search_test to turn-off memory tracking after OnLoad is called.
3. Fixing github workflows grouping
> fixing github integration tests

- build.sh
```
Module path: .build_release/libsearch.so
4495.2 
4495.2 You may want to run the unit tests by executing:
4495.2     ./build.sh --run-tests
4495.2 
4495.2 To load the module, execute the following command:
4495.2     valkey-server --loadmodule /opt/valkey-search/.build_release/libsearch.so
```
However the built binary is located in the `.build_release` repository
> Update printed binary file path

- testing/integration/CMakeLists.txt
Previously when running python integration tests, errors are suppressed so making it hard to debug issues.
> Don't suppress error when running python integration tests.

- build.sh
- cmake/Modules/valkey_search.cmake
- testing/CMakeLists.txt
- Use 'valkey_search_add_static_library' for 'testing_common' static library to make sure it uses the same build flags as other libraries
- build.sh: when running UT with ASan enabled, do not terminate after the first UT that fails
- build.sh: running a single UT now prints the execution output to the terminal
- build.sh: fixed wrong status message printed after a successful build
> More ASan build improvements

- src/valkey_search.cc
- src/valkey_search.h
- testing/valkey_search_test.cc
See [issue](https://github.com/valkey-io/valkey-search/issues/52). 
Tested by simulated a crash in a worker thread and verified that the generation info is succeeded.
> avoid unsafe code in ValkeySearch::Info  during crashdump

- src/indexes/vector_base.h
- src/indexes/vector_hnsw.cc
- src/indexes/vector_hnsw.h
- src/schema_manager.cc
- src/schema_manager.h
- src/valkey_search.cc
- src/valkey_search.h
- testing/vector_test.cc
Ran benchmark test with GIST dataset from ann-benchmark on valkey-search module resulted performance fluctuations and observed that lot of backfill/resize during the test. For large datasets the vector backfill process is triggered so frequent as it is hard coded to 10240. So making the constant to be configurable would help to adjust based on the number of documents be loaded and the frequency of backfill can be controlled based on the expected dataset size. this helps for reducing the indexing time and also perfomance fluctuation. 
Added '--resize-block-size' option in module load optins and this will be reflcted on kIndexSchemaBackfillBatchSize and kHNSWBlockSize for consistency and default value is 10240 as before. The values get modified for above default 10240 and does not reflect …
> Make backfill batch/block size configurable

- cmake/Modules/valkey_search.cmake
- vmsdk/src/testing_infra/module.h
Added missing mock method `RedisModule_RegisterNumericConfig` (A regression introduced in commit: 5e50c97e51f37a41021e766f70795fb4f53e86d8)
In addition, remove the `-S` from test binaries (to provide a better stack-traces when running under gdb)
> Fixed crash in UT

- src/valkey_search.cc
- vmsdk/src/concurrency.cc
- vmsdk/src/concurrency.h
- vmsdk/testing/concurrency_test.cc
On aarch64, `cpuinfo` output is different than the one generated by `amd64` machines. This fix uses `lscpu` to get the number of physical cores by parsing `lscpu` output and multiplying the number of sockets by the number of cores-per-socket. In case of an error, it will return the default from `std::thread::hardware_concurrency`.
Tests were added to `concurrency_test` binary
> Method `GetPhysicalCPUCoresCount` is broken for `Linux / aarch64`

- .devcontainer/Dockerfile
- .devcontainer/setup.sh
when i run 
```
id -g
id -gn
```
commands In My Mac OS, I got
```
20
staff
```
`ubuntu:stable` has already "staff" group. so when build docker got error
```
groupmod: group 'staff' already exists
```
If conflict with reserved group, then use default group in the script.
> chore: avoid reserved gid, group name when setup for local dev env

- vmsdk/src/thread_pool.cc
- vmsdk/src/thread_pool.h
- vmsdk/src/thread_safe_vector.h
- vmsdk/src/vector.h
- vmsdk/testing/thread_pool_test.cc
Extended `ThreadPool` class with a "Resize" method
which allows the caller to increase or reduce the
thread count at runtime. In order to reduce the thread count,
the ThreadPool class associates a metadata per running thread `Thread`
the thread, within its "main" loop, checks if it was signaled to exit.
If it does, than the thread leaves its main loop while moving itself to
a "pending join" queue. The idea is that at given interval (using existing
timer events) the engine will periodically call `ThreadPool::JoinTerminatedWorkers`
to join threads that were exit. 
The default `ThreadPool::JoinWorkers` now internally also calls `ThreadPool::JoinTerminatedWorkers`
Fixed flaky ThreadPool.priority test
Added new `Vector<T>` class which is a thread-safe wrapper around `std::vector` and provides …
> Dynamic thread pool

- src/commands/commands.h
- src/commands/ft._list.json
- src/commands/ft_create.cc
- src/commands/ft_dropindex.cc
- src/commands/ft_info.cc
- src/commands/ft_search.cc
- src/module_loader.cc
- vmsdk/src/module.cc
- vmsdk/src/module.h
- vmsdk/src/valkey_module_api/valkey_module.h
While the ACL enhancement introduced in valkey-search allows command filtering based on prefixes, the engine enforces ACL checks on incoming commands independently. Currently, there's a misalignment between the permissions used during command registration and the permissions evaluated by valkey-search’s prefix-based ACL. This mismatch can result in the engine blocking legitimate commands. For example, if a user is allowed to execute only slow commands, an FT.SEARCH invocation may be blocked by the engine because it wasn't registered with the slow ACL category.
I manually verified this PR and integration tests should be added in the future.
In addition, this PR sets `admin` permission to FT._LIST, [similarly](https://redis.io/docs/latest/commands/ft._list/) to RediSearch. This is needed to …
> Command registration permissions alignment with ACL prefix permissions

- src/commands/ft_search_parser.cc
Empty vector query clause leads to [accessing](https://github.com/valkey-io/valkey-search/blob/5001de38f1a39b1c10bf371a9746b5529ba901f1/src/commands/ft_search_parser.cc#L171) out of bounds memory
> Fixing empty vector query clause ft.search cmd parsing

- src/coordinator/metadata_manager.cc
- src/rdb_serialization.cc
- src/schema_manager.cc
Due to https://github.com/valkey-io/valkey/issues/2125 the IO context will not be freed which can trigger later assertions. We don't rely on it during saving so instead we now just use the background context for things like logging.
Fixes #142
> Use background context rather than IO context during Aux save.

- vmsdk/src/module_config.h
`ConfigBuilder`: keep `config_` as `shared_ptr` to make sure that the underlying pointer is free-ed once, in the unlikely event of `Build()` being called more than once.
> Module-Config: fix a possibility of a double free

- submodules/CMakeLists.txt
On some Linux distros, modules install their module `CMake` config under `lib64/` folder and not under `lib/` (for example `gRPC`). 
The current CMake code, always assume that CMake config files are placed in the `lib` folder.  With this fix, CMake will check for the existence of the CMake config file in both `lib/` & `lib64/` and will pick the correct path
> CMake fixes for CentOS / Fedora based machines

- vmsdk/src/module_config.h
build fails with DCMAKE_BUILD_TYPE=release on latest main branch as below.
```
[ 53%] Built target ft_create_parser
In file included from /home/ubuntu/shiv-vector-search/valkey-search/vmsdk/src/module_config.cc:29:
/home/ubuntu/shiv-vector-search/valkey-search/vmsdk/src/module_config.h: In function ‘vmsdk::config::ConfigBuilder<ValkeyT> vmsdk::config::Builder(Args&& ...)’:
/home/ubuntu/shiv-vector-search/valkey-search/vmsdk/src/module_config.h:351:19: error: static assertion failed: Unreachable
351 |     static_assert(false, "Unreachable");
|                   ^~~~~
In file included from /home/ubuntu/shiv-vector-search/valkey-search/vmsdk/src/thread_pool.cc:46:
/home/ubuntu/shiv-vector-search/valkey-search/vmsdk/src/module_config.h: In function ‘vmsdk::config::ConfigBuilder<ValkeyT> …
```
> fix compilation failure with DCMAKE_BUILD_TYPE=release option

- .devcontainer/Dockerfile
- .gitignore
- build.sh
- ci/build_ubuntu.sh
- ci/refresh_comp_db.sh
- submodules/package-submodules.sh
- Support for building with ASan deb files
- During CI build, pull the deb files from GitHub assets section
- `refresh_comp_db.sh` use the `ci/build_ubuntu.sh` script for faster build time
- Remove deb files from the repo
- When running tests with ASan enabled and error is encountered, make sure to exit with a non zero exit code
- In case of an ASan build & after a test failure, make sure that the file that contains the test output is cleared after dumping its content to stdout
Closes this issue: https://github.com/valkey-io/valkey-search/issues/116
> CI updates

- src/utils/patricia_tree.h
- testing/utils/patricia_tree_test.cc
In case multiple indexes are created for the same prefix the first index that will dropped - all of the subscribers associated with that prefix will be dropped.
Effectively making all these indexes "frozen"
This PR fixes issue: https://github.com/valkey-io/valkey-search/issues/124
> Fix bug resulting in no ingestion to indexes with the same prefix as a dropped index

- submodules/CMakeLists.txt
With this PR and in order to fix Linux Alpine build error (re2 library):
CMake, after pulling the `gRPC` submodule, will edit the file `re2.h` by replacing `mutable int32_t` into `mutable int`. 
See this upstream commit: https://github.com/google/re2/commit/b025c6a3ae05995660e3b882eb3277f4399ced1a
> Alpine Linux related fixes

- cmake/Modules/protobuf_generate.cmake
- cmake/Modules/valkey_search.cmake
- src/CMakeLists.txt
- src/coordinator/CMakeLists.txt
- src/indexes/CMakeLists.txt
- third_party/hnswlib/CMakeLists.txt
Invoke `protoc` directly and simplify the function
that generates `grpc` / `proto` files. This fixes the build issues on Linux Alpine on ARM
> Refactored protobuf generation code (cmake)

- vmsdk/testing/utils_test.cc
The test fails on AARCH architecture, this should work for all architectures.
> Fix DisplayAsSIBytes test

- integration/test_info.py
- src/valkey_search.cc
- vmsdk/src/CMakeLists.txt
- vmsdk/src/testing_infra/module.h
- vmsdk/src/thread_monitoring.cc
- vmsdk/src/thread_monitoring.h
- vmsdk/src/thread_pool.cc
- vmsdk/src/thread_pool.h
- vmsdk/src/thread_safe_vector.h
- vmsdk/testing/thread_pool_test.cc
Added new Thread monitoring class, that calculates thread CPU usage. The CPUs are collected and averaged, and published under a new info section called `search_cpu`.
The new metrics are:
`search_used_read_cpu`, `search_used_write_cpu`
> Add CPU metrics for reader and writer threads

- integration/test_query_parser.py
- src/commands/ft_search_parser.cc
- src/valkey_search_options.cc
- src/valkey_search_options.h
Add query string bytes limit using a module config. This control the size of the query string used in the FT.SEARCH command.
> Add query string bytes limit using a module config

- integration/run.sh
- integration/test_vss_basic.py
- integration/valkey_search_test_case.py
With this change:
- Added support for CME in valkey-test-framework
- Each test creates its own test folder under `/tmp/valkey-search-clusters/<TEST_NAME>/<PORT>`
> valkey-test-framework: support creating cluster

- testing/ft_info_test.cc
- vmsdk/src/utils.cc
- vmsdk/testing/utils_test.cc
Fix WrongArity function to wrap command names with single quotes for Valkey consistency
The `WrongArity` function in `vmsdk/src/utils.cc` generates error messages that don't match Valkey's standard formatting. Command names should be wrapped in single quotes to be consistent with Valkey's `commandCheckArity` function.
**Current behavior:**
```
ERR wrong number of arguments for FT.INFO command
```
**Expected behavior (matching Valkey standard):**
```
ERR wrong number of arguments for 'FT.INFO' command
```
Updated the `WrongArity` function to include single quotes around command names:
```cpp
// Before
std::string WrongArity(absl::string_view cmd) {
return absl::StrCat("ERR wrong number of arguments for ", cmd, " command");
}
// After  
std::string WrongArity(absl::string_view cmd) {
return …
```
> Fix WrongArity function to wrap command names with single quotes for Valkey consistency

- .vscode/settings.json
- src/index_schema.h
- src/indexes/CMakeLists.txt
- src/indexes/text/posting.cc
- src/indexes/text/posting.h
- testing/CMakeLists.txt
- testing/posting_test.cc
The Postings object maps a single stemmed word to the list of all (Key, Field, Position) triples where that word appears in the corpus. For each entry in the inverted term index, there is an instance of this structure which is used to contain the key/field/position information for each word.
```
Postings
├── std::map<Key, PositionMap> key_to_positions_
│
├── Key="document1"
│   └── PositionMap: std::map<Position, FieldMask*>
│       ├── Position=5  → FieldMask[fields 0,2] = 0b00000101
│       ├── Position=12 → FieldMask[field 1]    = 0b00000010  
│       └── Position=18 → FieldMask[fields 0,1,3] = 0b00001011
│
├── Key="document2"
│   └── PositionMap: std::map<Position, FieldMask*>
│       ├── Position=0  → FieldMask[fields 0,1] = 0b00000011
│       └── Position=3  → FieldMask[field 2] …
```
> Posting Object Implementation

- src/index_schema.cc
- src/index_schema.h
- src/indexes/CMakeLists.txt
- src/indexes/text.cc
- src/indexes/text.h
- src/indexes/text/posting.cc
- src/indexes/text/posting.h
- src/indexes/text/text_index.h
- testing/posting_test.cc
Building on top of #289 
```
class Text 
├── Inherits IndexBase
├── Implemented AddRecord API , placeholder for rest.
├── Text takes the whole index_schema_proto, text_index_proto, shared reference to the TextIndexSchema class, text field number as parameters
class TextIndex
├── Holds the prefix tree and optional suffix tree. (postings are shared between prefix and suffix tree
├── wrapper around the trees, we need to go via TextIndex to mutate on the tree , get word iterator, get path iterator
├── resides in the TextIndexSchema, One TextIndex per Schema. 
class TextIndexSchema
├── wrapper between IndexSchema and TextIndex. 
├── While initializing IndexBases per field/attribute if we encounter a text field and if TextIndexSchema reference doesn't already exist we initialize a Shared …
```
> Bridge some gaps in ingestion pipeline

- src/index_schema.cc
- src/indexes/text.cc
- src/indexes/text.h
- src/indexes/text/text_index.h
- testing/CMakeLists.txt
- testing/text_index_schema_test.cc
Provide a text field identifier number to the Text field objects on creation. update the total in text index schema level.
```
42827:M 08 Aug 2025 20:29:20.707 # <module> [notice], tid: 140734468454144, /local/home/ramvolet/Workspace/valkey-search/src/indexes/text/posting.cc:205: InsertPosting: field_index=0, total_fields=4
[New Thread 0x7ffeb7dff700 (LWP 43743)]
42827:M 08 Aug 2025 20:30:19.264 # <module> [notice], tid: 140734818658048, /local/home/ramvolet/Workspace/valkey-search/src/indexes/text/posting.cc:205: InsertPosting: field_index=2, total_fields=4
> Add text field number to the text field index

- integration/test_valkey_search_acl.py
Added ACL integration tests. The tests check the following:
- Check correctness for commands flags and categories (sanity check)
- Test with various users and verifies correct permissions
- Test for index with several prefixes and user that has access only to one of the prefixes. Test makes sure user has no access to that index.
This integration test class can be expanded in the future for more cases.
> Add ACL integration tests

- .github/workflows/integration_tests.yml
- build.sh
- integration/run.sh
- OSS integration tests retry is now default to 1. User can use --retries=N to control this.
- Use --retries=3 in CI builds.
> Build script fixes

- integration/test_fulltext.py
- src/indexes/text.cc
- src/indexes/text.h
- src/indexes/text/phrase.cc
- src/indexes/text/phrase.h
- src/indexes/text/posting.cc
- src/indexes/text/posting.h
- src/indexes/text/text_index.h
- testing/posting_test.cc
* KeyIterator can now take field specifications to filter on certain fields
* Updated PhraseIterator to search on only field specified in the query
* Use WITHOFFSETS as input for save_positions.
* Add integration test for full text search per field when word is present in different fields
> Address KeyIterator Gaps

- integration/test_info.py
Apparently, memory accounting doesn't work with ASAN. no surprise.
> Fix ASAN test failure

- src/indexes/text/radix_tree.h
- testing/radix_test.cc
Currently, if we pass an input to the WordIterator that partially matches the Compressed Node value when recursing through on the WordIterator and generating results, we do not amend the rest of the path; this results in distorted results. Example below. 
Let's say there is a tree structure like this
```
=== Tree Structure - Initial tree with cat, can, testing, test ===
Node[] BRANCH(2)
Node[c] COMPRESSED[a]
Node[ca] BRANCH(2)
Node[can] TARGET LEAF
Node[cat] TARGET LEAF
Node[t] COMPRESSED[est]
Node[test] TARGET COMPRESSED[ing]
Node[testing] TARGET LEAF
=== End Structure ===
```
When i create WordIterator like  GetWordIterator("ca") . It gave me "can" and "cat" correctly, because prefix "ca" is an exact match in radix tree. But when i created GetWordIterator("te") , it gave me "te" and …
> Minor fix in WordIterator to allow partial prefix match

- src/attribute_data_type.cc
- src/attribute_data_type.h
- src/commands/ft_create_parser.cc
- src/index_schema.cc
- src/query/response_generator.cc
- src/valkey_search.cc
- src/valkey_search.h
- testing/attribute_data_type_test.cc
- testing/common.h
- testing/query/response_generator_test.cc
- testing/valkey_search_test.cc
- vmsdk/src/module.cc
- vmsdk/src/module.h
- vmsdk/src/testing_infra/module.h
This change addresses the issue reported in [issue #255](https://github.com/valkey-io/valkey-search/issues/255).
Support for the JSON shared API is WIP and introduced in [this PR](https://github.com/valkey-io/valkey-json/pull/71).
To avoid introducing a hard dependency on a specific valkey-json release, the implementation is backward compatible: it prefers the new shared API if available, and falls back to VM_Call otherwise.
Once the valkey-json changes are included in an official release, we plan to deprecate the fallback logic and enforce valkey-json version that includes the new JSON shared API.
> Add support to retrieving JSON values via the JSON shared API

- src/commands/ft_create_parser.cc
- testing/ft_create_parser_test.cc
- testing/ft_create_test.cc
When using M=1, the server is crashing with an out of memory message.
Increased the minimum M value to be 2 instead of 1, and fixed the unit tests accordingly.
> Increase M minimum limit to 2

- vmsdk/src/module_config.cc
- vmsdk/src/module_config.h
Problem:
The `OnGetStringConfig` function was creating new `ValkeyModuleString` objects on every config get request without 
proper cleanup, causing memory leaks.
```
Indirect leak of 105 byte(s) in 2 object(s) allocated from:
#0 0x7f6e93d4457d in malloc (/lib64 libasan.so.4+0xd857d)
#1 0x69acb5 in ztrymalloc_usable_internal 
#2 0x69b009 in zmalloc_usable 
#3 0x69397d in _sdsnewlen
#4 0x694209 in sdsnewlen 
#5 0x6ec7df in createRawStringObject 
#6 0x6ece8b in createStringObject
#7 0x8b5feb in VM_CreateString
#8 0x7f6e81d138e5 in  (libsearch.so+0x2988e5)
#9 0x8e8c7e in getModuleStringConfig
#10 0x7aff0a in sdsConfigGet 
#11 0x7aa15c in configGetCommand
...
Solution:
Added caching mechanism with `GetCachedValkeyString` method and Added proper cleanup in destructor and when config values …
```
> fix memory leak at config get

- src/indexes/text/posting.cc
- src/indexes/text/posting.h
- src/utils/string_interning.h
Implement custom comparator for Postings::KeyIterator, which compares the actual key strings itself and not the addresses to keep it sorted. Necessary for search results to be displayed in lexical order of key strings.
> Lexical Ordering for Keys in Postings KeyIterator

- integration/ft_info_parser.py
- integration/test_fulltext.py
- src/index_schema.cc
- src/index_schema.h
- src/indexes/text.cc
- testing/ft_info_test.cc
This changes makes the FT.INFO more faithful with attributes and statistics in valkey-search module. We are doing this by removing any statics that were place holders made just to be compatible with redis search. We have also added additional statistics, added attributes and chaged the design of FT.INFO which we are going to show to the users. This is in continuation to the PR in the main branch where only attributes and statistics not related to fulltext are added.
> Update ft info

- src/indexes/text/radix_tree.h
- testing/radix_test.cc
Throwing out some very rough delete logic for the radix tree to unblock people if needed. I think the delete works but there is a bug in the word iterator causing `DeleteStructuralCases` to fail, but I ran out of time to look into it. I'll be back online by the weekend.
> Rough delete logic for the radix tree
